import { ArrayHelper } from "./array";
// Generated by CodiumAI

describe("ArrayHelper", () => {
  // Tests that merging two arrays successfully returns a new array with the combined elements
  it("should merge two arrays successfully", () => {
    expect(ArrayHelper.merge([1, 2, 3], [4, 5, 6]).length).toBe(6);
    expect(ArrayHelper.merge([1, 2, 3], [4, 5, 6])[5]).toBe(6);
  });

  // Tests that removing an item from an array successfully returns a new array without the specified item
  it("should remove an item from an array successfully", () => {
    expect(ArrayHelper.remove([1, 2, 3], 1).length).toBe(2);
    expect(ArrayHelper.remove([1, 2, 3], 1)[0]).toBe(2);
    expect(ArrayHelper.remove([1, 2, 3], 1)[1]).toBe(3);
  });

  // Tests that the removeAll function removes multiple items from an array correctly
  it("should remove multiple items from an array correctly", () => {
    expect(ArrayHelper.removeAll([1, 2, 3, 4, 5], [2, 4]).length).toBe(3);
    expect(ArrayHelper.removeAll([1, 2, 3, 4, 5], [2, 4])[0]).toBe(1);
    expect(ArrayHelper.removeAll([1, 2, 3, 4, 5], [2, 4])[1]).toBe(3);
    expect(ArrayHelper.removeAll([1, 2, 3, 4, 5], [2, 4])[2]).toBe(5);
  });

  // Tests that changing an item in an array successfully returns a new array with the specified item replaced
  it("should change an item in an array successfully", () => {
    expect(ArrayHelper.change([1, 2, 3], 1, 12).length).toBe(3);
    expect(ArrayHelper.change([1, 2, 3], 1, 12)[0]).toBe(12);
    expect(ArrayHelper.change([1, 2, 3], 1, 12)[1]).toBe(2);
    expect(ArrayHelper.change([1, 2, 3], 1, 12)[2]).toBe(3);
  });

  // Tests that merging two empty arrays returns an empty array
  it("should merge two empty arrays and return an empty array", () => {
    expect(ArrayHelper.merge([], []).length).toBe(0);
  });
});
